version: "3.9"

services:
  db:
    image: postgres:15
    container_name: expense-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expensedb
    ports:
      - "5432:5432"
    volumes:
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data

  expense-service:
    build: ./expense-service
    container_name: expense-service
    ports:
      - "5000:5000"  # service accessible on localhost:3000
    volumes:
      - ./expense-service:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/expensedb
      - PORT=5000
    depends_on:
      - db
